[package]
name = "zen"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.32.0"
egui_extras = { version = "0.32.0", features = ["syntect"] }
eframe = "0.32.0"
env_logger = "0.11.8"
rfd = "0.15.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
image = "0.25.6"
